baseURL: "https://ongaunter.netlify.app"
theme: "up-business-theme"
languageCode: "en-us"
canonifyURLs: true
relativeURLs: true

title: "Ong Aun Ter"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Up Business"
  description: "We specialize in providing services to desing websites, applications, build and maintain business for customers."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "3891 Ranchview Dr. Richardson, California 62639"
    - "4517 Washington Ave. Manchester, Kentucky 39495"

  contact:
    - "trungkienspktnd@gamail.com"
    - "207.555.0119"

  copyright: "© 2022 Up Business All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "About Me"
      url: "/about_me"
      weight: 2

    # - name: "Test"
    #   url: "/#"
    #   weight: 3

    - name: "Services"
      url: "/services"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5
    

  buttons:
    - name: "Book a call"
      url: "/message_me"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "About Me"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
  categories: "categories"
