baseURL: "https://ongaunter.netlify.app"
theme: "up-business-theme"
languageCode: "en-us"
canonifyURLs: true
relativeURLs: true

title: "Ong Aun Ter"

googleAnalytics: "G-S2JF4EMNMX"

summaryLength: 20

params:
  title: "Ong Aun Ter"
  description: "I can help you with Career Transition"
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "Kuala Lumpur, Malaysia"

  contact:
    - "ongaunter@gamail.com"

  # copyright: "© 2022 Up Business All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "About Me"
      url: "/about_me"
      weight: 2

    - name: "Career Quiz"
      url: "/read_more"
      weight: 3

    - name: "Services"
      url: "/services"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5
    

  buttons:
    - name: "Book a call"
      url: "/message_me"
      weight: 5
      pre: "btn btn-primary text-light"
      

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "About Me"
      url: "/#"
      weight: 2

    - name: "My Services"
      url: "/#"
      weight: 3

    # - name: "Pricing"
    #   url: "/#"
    #   weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
  categories: "categories"
